### ISSUE TITLE
Accessing type

### ISSUE THREAD

**Issue by jfedick** [paulca/paths_of_glory#1]
I need to access the types of achievements that a user accomplishes in order to display a picture along with each particular achievement. When I try to access it (via- @user.achievements.type), I get an error that says that it wants to return "array" (as in achievements is an array) instead of actually returning the elements in the type column of my database. Since every ruby object has a method called "type," my call to access the type column of the database fails. When I try to change the entry in the table, the paths_of_glory gem says it needs a type column in order to function properly. 

I'm not quite sure where to go from here in order to access that column in the database. Any suggestions?

**Comment by paulca** [comment]
It looks like you're calling type on the achievements array ... 

You should be able to call type on each individual achievement:

@user.achievements.each do |achievement|
  puts achievement.type.to_s
end

Hope this helps!

—P

**Comment by jfedick** [comment]
I get this error when I run your suggestion.

The single-table inheritance mechanism failed to locate the subclass: 'BadgeBetsPlaced'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Achievement.inheritance_column to use another column for that information.

**Comment by paulca** [comment]
Hmmmm. Have you set your load_paths correctly:

config.load_paths += %W( #{Rails.root}/app/models/achievements )

—P

**Comment by jfedick** [comment]
Yes. I copied and pasted it straight from your README. 

Any other suggestions?

**Comment by paulca** [comment]
What version of Rails are you on? Does the file badge_bets_placed.rb exist in app/models/achievements and does it define class BadgeBetsPlaced ?

—P

**Comment by jfedick** [comment]
Rails 2.3.5 and Yes.

class BadgeBetsPlaced < Achievement

**Comment by paulca** [comment]
In script/console, can you call:

BadgeBetsPlaced.all ?

It sounds like BadgeBetsPlaced isn't getting loaded or something.

the "type" column is intentional ... it uses Rails' in built single table inheritance for storing all the achievements in a single table.

**Comment by jfedick** [comment]
It looks like that is the problem. When I call BadgeBetsPlaced.all in console, I get a ton of errors that look like they have to do with the methods I use within the achievement model itself. I didn't work on that code, so I'll have to talk to the guy who did. Thanks for your help!

**Comment by paulca** [comment]
No worries, let me know how you get on.

—P

**Comment by jfedick** [comment]
Hey Paul, I'm back from vacation and working on the bug again. The BadgeBetsPlaced.all error is fixed but I still get the type error- 

The single-table inheritance mechanism failed to locate the subclass: 'BadgeBetsPlaced'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Achievement.inheritance_column to use another column for that information.

It specifically occurs because of this line-

@current_user.achievements.each do |badge|

Any new ideas on what might cause this?
