### ISSUE TITLE
Example App

### ISSUE THREAD

**Issue by aaronmase** [paulca/paths_of_glory#2]
This would be very useful.

**Comment by paulca** [comment]
Hi,

I do plan on getting around to this, but I've a few things to fix up and I want to add Rails 3 support first.

—P

**Comment by raid5** [comment]
So, does this current version not work with Rails 3 then? :/ I've been messing with designing my own achievement system but I'd prefer to use paths_of_glory if possible.

**Comment by paulca** [comment]
It doesn't work in Rails 3 as it is now, but I do have a version working that I need to extract, which I will do: I needed to figure my way around the new Rails 3 plugin API.

**Comment by raid5** [comment]
Awesome! I forked the current code and have been messing around with porting it to Rails 3 for some experience.
